# Generated by Django 4.0.5 on 2022-06-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkgamelist",
            options={"verbose_name": "Ссылка", "verbose_name_plural": "Ссылки"},
        ),
    ]
