# Generated by Django 4.0.5 on 2022-07-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_linktype_linkgamelist_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgamelist',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.linktype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='linkgamelist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ссылки'),
        ),
    ]
